### ISSUE TITLE
Specify whether storing enable_time_stamp TP is mandatory

### ISSUE THREAD

**Issue by dtikhonov** [huitema/quic-1wd#3]
The transport I-D 31 [states](https://tools.ietf.org/html/draft-ietf-quic-transport-31#section-7.4.1):

```
   The definition of a new transport parameter (Section 7.4.2) MUST
   specify whether storing the transport parameter for 0-RTT is
   mandatory, optional, or prohibited.  A client need not store a
   transport parameter it cannot process.
```

This information is missing from [draft-huitema-quic-ts-03](https://tools.ietf.org/html/draft-huitema-quic-ts-03).

**Comment by huitema** [comment]
Fixed in PR #7
