### ISSUE TITLE
Truth in advertising

### ISSUE THREAD

**Issue by martinthomson** [huitema/quic-1wd#4]
In practice, measuring one-way delay is not possible in a protocol like QUIC.  The draft framing is clear that this is about improving the ability of a sender to remove variation in return path delays.  This is good, but the title and headings imply something else, which is misleading.

**Comment by huitema** [comment]
Alternative title?

**Comment by huitema** [comment]
I have renamed the depot and reworked the README to reflect the current focus on a time stamp frame. Does that address your concern?

**Comment by martinthomson** [comment]
yes.
